apiVersion: v2
name: postgresql
description: PostgreSQL database for spring-k8s-gitops project
type: application
version: 1.0.0
appVersion: "18.1.0"

dependencies:
  - name: postgresql
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
