apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-api.fullname" . }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if .Values.externalDatabase.existingSecret }}
  {{- /* Password will be injected from existing secret */ -}}
  {{- else }}
  DB_PASSWORD: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ .Values.app.jwt.secret | b64enc | quote }}
