apiVersion: v2
name: grafana
description: Grafana visualization for spring-k8s-gitops project
type: application
version: 1.0.0
appVersion: "11.5.2"

dependencies:
  - name: grafana
    version: 10.5.8
    repository: https://grafana.github.io/helm-charts
