apiVersion: v2
name: spring-api
description: Helm chart for Spring API application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
