apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-blog-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: spring-k8s-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ouznoreyni/spring-k8s-gitops.git
    targetRevision: HEAD
    path: k8s/charts/frontend-ui
    helm:
      releaseName: blog-frontend
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
