apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: spring-k8s-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ouznoreyni/spring-k8s-gitops.git
    targetRevision: HEAD
    path: k8s/charts/harbor
    helm:
      releaseName: container-registry
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
